name: test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - run: mvn package
      - uses: softprops/action-gh-release@v2.0.8
        with:
          files: /target/*.jar
          body: "Binaries of the Costum Spring Petclinic"
          tag_name: ${{ github.ref_name }}
