name: test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  checkout:
    runs-on: self-hosted
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - run: gh --version
        
